export const DASHBOARD_ROUTES: Record<string, string> = {
  '/admin/dashboard': 'Dashboard',
  '/admin/sub-dashboard': 'Sub Dashboard',
  '/admin/properties': 'Properties',
  '/admin/users': 'Users',
  '/admin/reported-content': 'Reported Content',
  '/admin/revenue': 'Revenue',
  '/admin/top-agents': 'Top Agents',
  '/admin/messages': 'Messages',
  '/seller/dashboard': 'Dashboard',
  '/seller/properties': 'My Properties',
  '/seller/inquiries': 'Inquiries',
  '/seller/pricing': 'Pricing',
  '/seller/top-performing': 'Top Performing',
  '/dashboard': 'Overview',
  '/dashboard/properties/new': 'Add Property',
  '/messages': 'Messages',
  '/favorites': 'Favorites',
  '/account': 'Account Settings',
};
